openapi: '3.0.0'

# =============================================================================

info:
  title: 'Seedy FIUBA API Gateway'
  description: >
    Part of the **Seedy FIUBA Project** ([view it on GitHub](https://github.com/orgs/SeedyFiuba-G8/)).
  version: '1.0.0'

# =============================================================================

servers:
  - url: https://sf-tdp2-gateway.herokuapp.com/
    description: 'Production'
  - url: https://sf-tdp2-gateway-dev.herokuapp.com/
    description: 'Staging'
  - url: http://localhost:3000/
    description: 'Local development'

# =============================================================================

tags:
  - name: Admins
  - name: Users
  - name: Projects
  - name: Status

# =============================================================================

paths:
  # USERS
  /user:
    get:
      summary: Get all users
      description: Get info from every user (only for admins).
      security:
        - bearerAuth: []
      tags:
        - Users
      responses:
        200:
          $ref: '#/components/responses/getAllUsers'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        409:
          $ref: '#/components/responses/409'
        500:
          $ref: '#/components/responses/500'

    post:
      summary: Register a new user
      description: Allows users to create a new basic account by email.
      tags:
        - Users
      requestBody:
        $ref: '#/components/requestBodies/postUser'
      responses:
        201:
          description: 'User was registered successfully.'
        400:
          $ref: '#/components/responses/400'
        409:
          $ref: '#/components/responses/409'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  /user/session:
    post:
      summary: Log in an user session
      description: Allows users to log in to their account in a new session.
      tags:
        - Users
      requestBody:
        $ref: '#/components/requestBodies/postSession'
      responses:
        200:
          $ref: '#/components/responses/postSession'
        400:
          $ref: '#/components/responses/400'
        409:
          $ref: '#/components/responses/409'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  # ADMINS
  /admin:
    post:
      summary: Register a new admin
      description: >
        Allows to add new admins to the webadmin system.

        [TEMP: Process will change later. A link will be send to the
        email provided and the user will be able to create an admin
        account using that link.]
      security:
        - bearerAuth: []
      tags:
        - Admins
      requestBody:
        $ref: '#/components/requestBodies/postAdmin'
      responses:
        201:
          description: 'Admin was registered successfully.'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        409:
          $ref: '#/components/responses/409'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  /admin/session:
    post:
      summary: Log in an admin session
      description: Allows admins to log in to their account in a new session.
      tags:
        - Admins
      requestBody:
        $ref: '#/components/requestBodies/postSession'
      responses:
        200:
          $ref: '#/components/responses/postSession'
        400:
          $ref: '#/components/responses/400'
        409:
          $ref: '#/components/responses/409'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  # PROJECTS
  /project:
    get:
      summary: Get all projects (optionally, of a specified user)
      description: Get info from every project (of the app/of the user).
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: userId
          required: false
          schema:
            type: string
          description: The userId of whom we want to retrieve projects.
      tags:
        - Projects
      responses:
        200:
          $ref: '#/components/responses/getAllProjects'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

    post:
      summary: Create a new project
      description: Allows an entrepeneur user to create a new project.
      security:
        - bearerAuth: []
      tags:
        - Projects
      requestBody:
        $ref: '#/components/requestBodies/postProject'
      responses:
        200:
          $ref: '#/components/responses/postProject'
        400:
          $ref: '#/components/responses/400'
        409:
          $ref: '#/components/responses/409'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  /project/{projectId}:
    get:
      summary: Get a project by id
      description: Allos a user to get retrieve a project's information by its id.
      security:
        - bearerAuth: []
      tags:
        - Projects
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description: uuid of the project to retrieve
      responses:
        200:
          $ref: '#/components/responses/getProject'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

    put:
      summary: Modify the information of the project.
      description: Allows an owner of a project or an admin to modify the information of a project.
      security:
        - bearerAuth: []
      tags:
        - Projects
      requestBody:
        $ref: '#/components/requestBodies/putProject'
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description: uuid of the project to modify
      responses:
        200:
          $ref: '#/components/responses/putProject'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        404:
          $ref: '#/components/responses/404'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

    delete:
      summary: Delete a project by ID
      description: Allows an owner of a project or an admin to delete a project.
      security:
        - bearerAuth: []
      tags:
        - Projects
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description: uuid of the project to delete
      responses:
        200:
          $ref: '#/components/responses/deleteProject'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        404:
          $ref: '#/components/responses/404'
        415:
          $ref: '#/components/responses/415'
        500:
          $ref: '#/components/responses/500'

  # STATUS
  /health:
    get:
      tags:
        - Status
      responses:
        200:
          $ref: '#/components/responses/health'
        400:
          $ref: '#/components/responses/400'
        415:
          $ref: '#/components/responses/415'

  /ping:
    get:
      tags:
        - Status
      responses:
        200:
          $ref: '#/components/responses/ping'
        400:
          $ref: '#/components/responses/400'
        415:
          $ref: '#/components/responses/415'

  /pingAll:
    get:
      tags:
        - Status
      responses:
        200:
          $ref: '#/components/responses/pingAll'
        400:
          $ref: '#/components/responses/400'
        415:
          $ref: '#/components/responses/415'

# =============================================================================

components:
  # ---------------------------------------------------------------------------
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    # ERRORS
    400:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    401:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    403:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    404:
      description: Not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    409:
      description: Conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    415:
      description: Unsupported Media Type.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    500:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    # USERS
    getAllUsers:
      description: Users info retrieved successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AllUsers'

    # COMMON
    postSession:
      description: Logged in successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'

    # PROJECTS
    getAllProjects:
      description: Projects info retrieved successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AllProjects'

    getProject:
      description: Project info retrieved successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Project'

    postProject:
      description: Project created successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectId'

    putProject:
      description: Project modified successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectId'

    deleteProject:
      description: Project deleted successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectId'

    # STATUS
    health:
      description: Microservice general health state reported.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Health'

    ping:
      description: Server is active.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ping'

    pingAll:
      description: Server and its services are active..
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PingAll'

  # ---------------------------------------------------------------------------
  requestBodies:
    # USERS
    postUser:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterData'

    # ADMINS
    postAdmin:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AdminRegisterData'

    # PROJECTS
    postProject:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostProjectData'

    putProject:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutProjectData'

    # COMMON
    postSession:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/LoginData'
              - $ref: '#/components/schemas/FBLoginData'

  # ---------------------------------------------------------------------------
  schemas:
    # GENERAL
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
            name:
              type: string
            message:
              type: string
            errors:
              type: object
            data:
              type: object
          required:
            - status
            - name
      required:
        - error

    # USERS
    AllUsers:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - users

    User:
      type: object
      properties:
        id:
          type: string
          example: 'SomePassword123'
        email:
          type: string
          example: 'memis_pomofot@gmail.com'
        banned:
          type: boolean
          example: false
        firstName:
          type: string
          example: 'Memis'
        lastName:
          type: string
          example: 'Pomofot'
        signupDate:
          type: string
          example: '2021-06-13T21:29:29.340Z'
      required:
        - id
        - email
        - banned
        - firstName
        - lastName
        - signupDate

    UserRegisterData:
      type: object
      properties:
        email:
          type: string
          example: 'memis_pomofot@gmail.com'
        password:
          type: string
          example: 'SomePassword123'
        firstName:
          type: string
          example: 'Memis'
        lastName:
          type: string
          example: 'Pomofot'
      required:
        - email
        - password
        - firstName
        - lastName

    # ADMINS
    AdminRegisterData:
      type: object
      properties:
        email:
          type: string
          example: 'memis_pomofot@gmail.com'
        password:
          type: string
          example: 'SomePassword123'
      required:
        - email
        - password

    # PROJECTS
    AllProjects:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
      required:
        - projects

    Project:
      type: object
      properties:
        id:
          type: string
          example: '670b9562-b30d-52d5-b827-655787665500'
        userId:
          type: string
          example: '670b9562-b30d-52d5-b827-655787665500'
        title:
          type: string
          example: 'Prohibir la utilizacion de Winbugs globalmente'
        description:
          type: string
          example: 'No puede ser que haya gente que use Winbugs'
        type:
          type: string
          example: 'social'
        objective:
          type: string
          example: 'Salvar a la gente de esta maldicion'
        country:
          type: string
          example: 'Argentina'
        city:
          type: string
          example: 'Buenos Aires'
        publishedOn:
          type: string
          example: 'Sun Jun 06 2021 19:27:45 GMT-0300 (Argentina Standard Time)' #Date.toString()
        finalizedBy:
          type: string
          example: 'Sun Jun 06 2021 19:27:45 GMT-0300 (Argentina Standard Time)' #Date.toString()
      required:
        - id
        - userId
        - title
        - description
        - type
        - objective
        - country
        - city
        - publishedOn
        - finalizedBy

    PostProjectData:
      type: object
      properties:
        title:
          type: string
          example: 'Prohibir la utilizacion de Winbugs globalmente'
        description:
          type: string
          example: 'No puede ser que haya gente que use Winbugs'
        type:
          type: string
          example: 'social'
        objective:
          type: string
          example: 'Salvar a la gente de esta maldicion'
        country:
          type: string
          example: 'Argentina'
        city:
          type: string
          example: 'Buenos Aires'
        finalizedBy:
          type: string
          example: 'Sun Jun 06 2021 19:27:45 GMT-0300 (Argentina Standard Time)' #Date.toString()
      required:
        - title
        - description
        - type
        - objective
        - country
        - city
        - finalizedBy

    PutProjectData:
      type: object
      properties:
        title:
          type: string
          example: 'Prohibir la utilizacion de Winbugs globalmente'
        description:
          type: string
          example: 'No puede ser que haya gente que use Winbugs'
        type:
          type: string
          example: 'social'
        objective:
          type: string
          example: 'Salvar a la gente de esta maldicion'
        country:
          type: string
          example: 'Argentina'
        city:
          type: string
          example: 'Buenos Aires'
        finalizedBy:
          type: string
          example: 'Sun Jun 06 2021 19:27:45 GMT-0300 (Argentina Standard Time)' #Date.toString()

    ProjectId:
      type: object
      properties:
        id:
          type: string
          example: '670b9562-b30d-52d5-b827-655787665500'
      required:
        - id

    # COMMON
    LoginData:
      type: object
      properties:
        email:
          type: string
          example: 'memis_pomofot@gmail.com'
        password:
          type: string
          example: 'SomePassword123'
      required:
        - email
        - password

    FBLoginData:
      type: object
      properties:
        fbToken:
          type: string
          example: 'EAAHTZAxeFHeUBACOZArY9H3yMDXtG7NF7K85VGt43keuBxd5LgAUz7gdCKdyyZCVGNGNqMZBy0J6HjlkldhIFm4RZBIPhqN0HSiZAbBvEsNIOIdhkzVmI1x6FWhRBtXORs1fXEyZCnkIPZCZCNVCaxbgisI1WjOyPRmYTCuGIpx014MY0FTYQxBXt7xr25ghdZChywWZAISf1escFnA1vVrBJylBXUEpt29Yvh557Ac0E8QYgZDZD'
      required:
        - fbToken

    Session:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      required:
        - id
        - token

    # STATUS
    Ping:
      type: object
      properties:
        status:
          type: string
          example: 'ok'
      required:
        - status

    PingAll:
      type: object
      properties:
        status:
          type: string
          example: 'ok'
        services:
          type: object
          properties:
            apikeys:
              type: string
              example: 'ok'
            core:
              type: string
              example: 'ok'
            users:
              type: string
              example: 'ok'

    Health:
      type: object
      properties:
        status:
          type: string
          example: 'UP'
        services:
          type: object
          properties:
            apikeys:
              type: object
              example: { 'database': 'UP' }
            core:
              type: object
              example: { 'database': 'UP' }
            users:
              type: object
              example: { 'database': 'UP' }
          required:
            - apikeys
            - core
            - users
      required:
        - status
        - services
#
# =============================================================================
